### ISSUE TITLE
reactnative: add android support

### ISSUE THREAD

**Issue by leordev** [TBD54566975/bundler-bonanza#66]
Right now we only test for ios

I attempted a quickstab here #64 but it failed, we need to make sure android works locally I think...

**Comment by shamilovtim** [comment]
Given that web5 only ships pure JS packages I think this is probably unnecessary. I think this repo should probably stick to smoke testing web5-js and dwn-js (and using iOS to do so). The wallet on the other hand can do the heavy lifting of e2e testing the native platforms (ios/android)
